Prettified the code
Enigmatis/polaris-middlewares pull request #3
Opened 2019-11-05 09:02 UTC by osher-sade

2019-11-06 10:25 UTC, chenshoo requested changes

2019-11-06 10:25 UTC, chenshoo commented on src/data-version/data-version-middleware.ts
> +const dataVersionHeaderName: string = 'data-version';
create header names in common and import from there

2019-11-06 10:25 UTC, chenshoo commented on src/data-version/data-version-middleware.ts
> +        // assert that it has no root (so it is the root)
remove doc

2019-11-06 10:25 UTC, chenshoo commented on src/index.ts
> +import { ExtensionsPlugin } from './plugins/extensions-plugin';
change to export directly

2019-11-06 10:25 UTC, chenshoo commented on test/data-version/data-version-middleware.test.ts
> +        it('a single entity is resolved, no filter should be applied', async () => {
filter should be applied if its root

2019-11-06 10:25 UTC, chenshoo commented on src/data-version/data-version-middleware.ts
>          } else {
add check on single entity from root

2019-11-11 09:19 UTC, chenshoo requested changes

2019-11-11 09:19 UTC, chenshoo commented on src/listeners/extensions-listener.ts
> +                    const result = await this.dataVersionRepository.find();
use findOne
if (result)
result.value

2019-11-11 09:19 UTC, chenshoo commented on src/realities/realities-middleware.ts
> +        ? context.requestHeaders.realityId
context.requestHeaders.realityId || 0

2019-11-11 09:19 UTC, chenshoo commented on src/realities/realities-middleware.ts
> +            if (noRealityIdOrSameAsHeader(result)) return result;
curly braces, run lint:fix

2019-11-11 11:17 UTC, osher-sade commented on src/listeners/extensions-listener.ts
> +                    const result = await this.dataVersionRepository.find();
should i pass argument to `findOne`?

2019-11-11 12:35 UTC, chenshoo approved these changes

2019-11-11 12:35 UTC, merged

2019-11-11 12:39 UTC, osher-sade commented
:tada: This PR is included in version 1.0.1 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@enigmatis/polaris-middlewares)
- [GitHub release](https://github.com/Enigmatis/polaris-middlewares/releases/tag/v1.0.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: